
services:

  # Service API Drogon
  auth-service-api:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth-container
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME_FILE: /run/secrets/auth_db_name
      DB_USER_FILE: /run/secrets/auth_db_user
      DB_PASSWORD_FILE: /run/secrets/auth_db_password
    secrets:
      - auth_db_name
      - auth_db_user
      - auth_db_password

  # Service PostgreSQL
  db:
    image: postgres:15
    container_name: auth-db
    env_file:
      - ./config/auth-service.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - auth_db_name
      - auth_db_user
      - auth_db_password

# Volumes Docker
volumes:
  auth-volumes:
  db-data:

secrets:
  auth_db_name:
    file: ./secrets/auth_db_name.txt
  auth_db_user:
    file: ./secrets/auth_db_user.txt
  auth_db_password:
    file: ./secrets/auth_db_password.txt